### ISSUE TITLE
Assist microphone - distored voice 

### ISSUE THREAD

**Issue by makaronpl** [rhasspy/hassio-addons#23]
Hello, I have problem.
 I am using the ‘Assist Microphone’ to recognize the wake word.
The wake word functionality is working properly. However, I am encountering an issue with the response; the voice is sped up and distorted, and I have error in the log:
'ALSA lib pcm.c:8570:(snd_pcm_recover) underrun occurred.'

My operating system version is 10.5,
Home Assistant Core version 2023.9.2.

I am using a Jabra Speak 510 for both my speaker and microphone.

**Comment by makaronpl** [comment]
when I use rhasppy 2.5 the voice is ok.

**Comment by BlackCube4** [comment]
My audio output is also distorted, but how did you even get a TTS response? I only get the “awake" and "done” sound effects :/

**Comment by Lampyridae1984** [comment]
+1

Using Anker PowerConf S330 Analog Stereo (latest firmware)

**Comment by ms1design** [comment]
Possibly the same issue here: https://github.com/rhasspy/hassio-addons/issues/26

**Comment by BlackCube4** [comment]
> My audio output is also distorted, but how did you even get a TTS response? I only get the “awake" and "done” sound effects :/

My issue is now solved :))

**Comment by synesthesiam** [comment]
@makaronpl Is this resolved by upgrade the add-on?

**Comment by Lampyridae1984** [comment]
> @makaronpl Is this resolved by upgrade the add-on?

Well it's mostly resolved for me at least. The big distortion and increased playback speed is completely gone, but there are still som static pops when the Assistant answers (while the audio is coming through the speaker). The log doesn't show any issues.

Any advice on how to remedy/improve the static during playback?

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service assist_microphone: starting
s6-rc: info: service assist_microphone successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Recording raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
```

**Comment by Lampyridae1984** [comment]
@synesthesiam Sorry, I take that back, it's still not working properly. I did some more testing today, when everyone was awake and this is what happens:

After saying the wake word, the Awake and Done sounds are played back to back, and are then followed by the answer "I'm sorry, I didn't understand that."

Eventually it stopped working all together and I get this error in the log:

```
ConnectionResetError: Cannot write to closing transport
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-17931' coro=<ClientWebSocketResponse.send_bytes() done, defined at /usr/local/lib/python3.11/dist-packages/aiohttp/client_ws.py:153> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client_ws.py", line 156, in send_bytes
    await self._writer.send(data, binary=True, compress=compress)
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/http_websocket.py", line 688, in send
    await self._send_frame(message, WSMsgType.BINARY, compress)
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/http_websocket.py", line 601, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-17933' coro=<ClientWebSocketResponse.send_bytes() done, defined at /usr/local/lib/python3.11/dist-packages/aiohttp/client_ws.py:153> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client_ws.py", line 156, in send_bytes
    await self._writer.send(data, binary=True, compress=compress)
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/http_websocket.py", line 688, in send
    await self._send_frame(message, WSMsgType.BINARY, compress)
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/http_websocket.py", line 601, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

After restarting both HAOS and the HA Yellow, It no longer listens. there seems to be a connection issue.

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service assist_microphone: starting
s6-rc: info: service assist_microphone successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Recording raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
ERROR:homeassistant_satellite.remote:
```

**Comment by makaronpl** [comment]
> @makaronpl Is this resolved by upgrade the add-on?

Yes, problem solved, thank you

**Comment by Lampyridae1984** [comment]
> > @makaronpl Is this resolved by upgrade the add-on?
> 
> Yes, problem solved, thank you

Did you update the firmware of the S330? I'm running the latest, but I'm not sure that it has anything to do with my continued issue.

**Comment by synesthesiam** [comment]
@Lampyridae1984 What hardware are you running HA on?

**Comment by Lampyridae1984** [comment]
> @Lampyridae1984 What hardware are you running HA on?

Home Assistant Yellow with a CM4 8GB Lite and a NVMe.

**Comment by ms1design** [comment]
Hey @Lampyridae1984 try that:
- definitely update **Anker** speaker to the last firmware, in latest release they fixed a lot of sound distortion (you would need to connect it to pc, upgrade is not working with mobile app)
- restart **home assistant**
- check if **openWakeWord/percupine** is running without errors (restart otherwise)
- check if the correct open word is selected in the **Assist Conversion Settings**
- check if **Assist Microphone Add-on** i running without issues (restart otherwise)
- In **Assist Microphone Add-on Configuration** screen make sure to enter the Assist Conversation Pipeline name (“Home Assistant” as default) which will be used with voice control
- In **Assist Microphone Add-on Configuration** screen make sure to select Anker S330 in Audio section
- As the last step make sure that **Wyoming Integration** in HA is working without issues, can be reloaded just in case

It there are no errors in any of addons then it should work - it is for me :) Fingers crossed!

The small issues Ive got is sometimes the Assist Microphone Add-on is playing 5x done sound just one-by-one which prevents me from running it at the full scale.

**Comment by Lampyridae1984** [comment]
@ms1design I already did update the S330 to the latest firmware. All add-ons seem to have started as expected, but it still does not work. After uttering the wake-up-word, both the 'Awake' and 'Done' audio files are played back to back, followed by the respons: "Sorry, I couldn't understand that."

I've also had issues with crashes of the add-on (as described above) and once it managed to freeze HA.

**Comment by ms1design** [comment]
@Lampyridae1984 try to enable debug mode & path to save debug wave files in /share HA host dir in Assist Mic addon. Confirm that sound is recorded without any distortions which could affect the STT

**Comment by Lampyridae1984** [comment]
> @Lampyridae1984 try to enable debug mode & path to save debug wave files in /share HA host dir in Assist Mic addon. Confirm that sound is recorded without any distortions which could affect the STT

The recording/-s are absolutely flawless: loud, clear and no distortions whatsoever.

**Comment by ms1design** [comment]
Did you set the “Pipeline” in Assist Mic Addon? This is the last of my ideas :) Maybe the creator(s) could give any advice?

**Comment by Lampyridae1984** [comment]
> Did you set the “Pipeline” in Assist Mic Addon? This is the last of my ideas :) Maybe the creator(s) could give any advice?

Yes, I've tried it with and without. I have three pipelines configured, two are over Nabu Casa Cloud (English and Swedish) and one is local (English). None seem to work.

**Comment by Lampyridae1984** [comment]
> Edit: @Lampyridae1984 you can also log in into HA Terminal using ssh and check the output of ‘ha audio log’. One thing I also did is selecting audio profile for Anker using ‘ha audio profile’ command. Both to analog.

How do you do that, what command did you type? And how did you change profile? Is there some documentation I can look at?

**Comment by Lampyridae1984** [comment]
Apparently this profile is active:

```
- active: true
  description: Analog Stereo Duplex
  name: output:analog-stereo+input:analog-stereo
```

**Comment by Lampyridae1984** [comment]
Something tells me that there are some issues...

```
➜  ~ ha audio log
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/alsa-mixer.sh
[16:59:46] INFO: Adjust ALSA mixer settings for /dev/snd/controlC0
[16:59:48] INFO: Adjust ALSA mixer settings for /dev/snd/controlC1
cont-init: info: /etc/cont-init.d/alsa-mixer.sh exited 0
cont-init: info: running /etc/cont-init.d/filesystem.sh
cont-init: info: /etc/cont-init.d/filesystem.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun alsa (no readiness notification)
services-up: info: copying legacy longrun pulseaudio (no readiness notification)
s6-rc: info: service legacy-services successfully started
W: [pulseaudio] main.c: Running in system mode, but --disallow-module-loading not set.
W: [pulseaudio] main.c: Home directory of user 'root' is not '/var/run/pulse', ignoring.
W: [pulseaudio] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
W: [pulseaudio] main.c: OK, so you are running PA in system mode. Please make sure that you actually do want to do that.
W: [pulseaudio] main.c: Please read http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/WhatIsWrongWithSystemWide/ for an explanation why system mode is usually a bad idea.
W: [pulseaudio] module-udev-detect.c: Failed to open /proc/asound/card1: No such file or directory
W: [pulseaudio] module-udev-detect.c: Failed to open /proc/asound/card0: No such file or directory
E: [pulseaudio] module-rescue-streams.c: module-rescue-stream is obsolete and should no longer be loaded. Please remove it from your configuration.
➜  ~
```

**Comment by ms1design** [comment]
@Lampyridae1984 the output of `ha audio log` is similar to mine. I don't see anything that pops out from the logs. Please use the correct name of used Assist Pipeline in the Assist Configuration. In my opinion it's important to work. You should enter there the value from "name" field ("Home Assistant Cloud" in this example):

<img width="628" alt="Screenshot 2023-10-15 at 16 37 35" src="https://github.com/rhasspy/hassio-addons/assets/24204300/79b722a3-76d7-4b85-84a7-433d8e5bd2fb">

**Comment by Lampyridae1984** [comment]
> You should enter there the value from "name" field ("Home Assistant Cloud" in this example):

Yes, that is exactly what I'm using. The S330 hears me saying the wake-up-word, then starts playing the 'Awake' and 'Done' wave file in quick succession followed by saying: "Sorry, I couldn't understand that."

**Comment by Lampyridae1984** [comment]
@ms1design Are you running HA in docker or as OS?

**Comment by ms1design** [comment]
@Lampyridae1984 I'm running HA OS in Proxmox VM. Maybe the intent of recorded audio command is not recognised? You can check that in: HA > Developer Tools > Assist. 

I have a Local LLM connected to the Assist Pipeline so instead of the "Sorry, I couldn't understand that." whenever the intent is not recognised I hear the response from my Local LLM saying something based on the wider context (it's more user friendly and I can chat with AI).

**Comment by Lampyridae1984** [comment]
> @Lampyridae1984 I'm running HA OS in Proxmox VM. Maybe the intent of recorded audio command is not recognised? You can check that in: HA > Developer Tools > Assist.

Nope, works just fine. I'm completely at a loss.

```
{
  "results": [
    {
      "sentence": "Turn on Apple TV",
      "language": "en",
      "result": {
        "intent": {
          "name": "HassTurnOn"
        },
        "slots": {
          "name": "apple tv"
        },
        "details": {
          "name": {
            "name": "name",
            "value": "apple tv",
            "text": "apple tv"
          }
        },
        "targets": {
          "switch.apple_tv_toggle": {
            "matched": true
          }
        }
      }
    }
  ]
}
```

**Comment by ms1design** [comment]
Ok, I'm lost @Lampyridae1984 - from everything we went together today it's makes me think that everything should be correct 🤔 Did you asked also on the proper section of HA Community Forum?

@synesthesiam any advice...?

**Comment by Lampyridae1984** [comment]
> Edit: @Lampyridae1984 noticed last thing with my Assis Mic Add-on configuration - I have **VAD** turned off.

I've tried with and without.

> Ok, I'm lost @Lampyridae1984 - from everything we went together today it's makes me think that everything should be correct 🤔 Did you asked also on the proper section of HA Community Forum? Maybe over there someone would have any similar issues...

I'm searching at the moment. Thank you for all the help!

**Comment by Lampyridae1984** [comment]
OMG! I think I found the issue.

I randomly decided to add 'assist_pipeline:' to my configuration.yaml, even thou 'default_config:' should load the pipeline configuration automatically when running Home Assistant as an OS. And _**Lo and behold**_, after rebooting HA OS it finally worked. I managed to get the Assistant to toggle a switch several times.

I then reversed my changes, so that I only have 'default_config:' in my configuration. After reboot everything still works as it should. I'm guessing something happened during a backup recovery last week, so that the Assist pipeline wasn't loading properly by default.

I'm **_not_** (!) yet willing to call it fixed before I had a chance to test it a couple of days, but it definitely seems promising.

The issues I'm still having at the moment are that sometimes (quite randomly) the 'Awake' sound file plays repeatedly without having said the wake-up-word and that I still have some static pops while the Assistant is answering.

When the 'Awake' sound file is played repeatedly back to back, I get this error:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service assist_microphone: starting
s6-rc: info: service assist_microphone successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Recording raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
ERROR:homeassistant_satellite.remote:
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
```

**Comment by Lampyridae1984** [comment]
After some extensive testing, finally, everything seems to work fairly good (except for the previously mentioned static audio och random 'Wake' sound playback). 👍🏻✌🏻

**Comment by TB-SE** [comment]
@makaronpl are you still experiencing some static noice with your Anker S330? Like before, during or after the Voice Assistant answers?

**Comment by TB-SE** [comment]
> Please try the official Assist Microphone add-on: https://github.com/home-assistant/addons/tree/master/assist_microphone

It's still an issue with the addon, static/popping sounds directly before and after the respons is played through the speaker. 🤷🏻‍♂️

**Comment by synesthesiam** [comment]
Odd, I have the Anker S330 as well and I don't experience popping sounds. There will be an update a bit later that will clean up some of the sound conversion code.

**Comment by TB-SE** [comment]
> Odd, I have the Anker S330 as well and I don't experience popping sounds. There will be an update a bit later that will clean up some of the sound conversion code.

Ok, interresting. Well as far as I know and have observed, my S330 works perfectly fine when I use it with for example Windows. I've tried unistalling everything connected to Assist (Wyoming, Piper, openWakeWord etc.), but nothing seems to mitigate the issue. I'll just wait and see what happens with the coming update. 👍🏻
