### ISSUE TITLE
Pipeline fails to start for Assist Microphone 

### ISSUE THREAD

**Issue by smarthomecircle** [rhasspy/hassio-addons#24]
So I am using the Assist Microphone add on to use my usb microphone. 

I have installed openwakeword addon ,and whisper. 
I am running this on Home Assistant OS 2023.10.2

I have configured the assist pipeline this way.
<img width="447" alt="image" src="https://github.com/rhasspy/hassio-addons/assets/136709923/063d90f4-df6f-4612-ac0c-8b3ab0983404">

I am able to run the pipe line using voice from the Home Assistant Companion App. So the Pipeline is working properly to turn on a light. 

But when I try to do the same with the Wake work "alexa" , it does not work . 
I see an error while invoking the pipeline in the Assist Microphone add on.

Here is the log of the Assist Microphone add on

```
DEBUG:__main__:Speech detected
DEBUG:homeassistant_satellite.remote:{'type': 'auth_required', 'ha_version': '2023.10.2'}
DEBUG:homeassistant_satellite.remote:{'type': 'auth_ok', 'ha_version': '2023.10.2'}
DEBUG:homeassistant_satellite.remote:{'id': 1, 'type': 'result', 'success': False, 'error': {'code': 'unknown_error', 'message': 'Unknown error'}}
ERROR:__main__:Unexpected error
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/__main__.py", line 193, in main
    async for _timestamp, event_type, event_data in stream(
  File "/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/remote.py", line 35, in stream
    message_id, handler_id = await _start_pipeline(
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/remote.py", line 119, in _start_pipeline
    assert msg["success"], "Pipeline failed to run"
AssertionError: Pipeline failed to run
DEBUG:__main__:Waiting for speech

DEBUG:__main__:Speech detected
DEBUG:homeassistant_satellite.remote:{'type': 'auth_required', 'ha_version': '2023.10.2'}
DEBUG:homeassistant_satellite.remote:{'type': 'auth_ok', 'ha_version': '2023.10.2'}
DEBUG:homeassistant_satellite.remote:{'id': 1, 'type': 'result', 'success': False, 'error': {'code': 'unknown_error', 'message': 'Unknown error'}}
ERROR:__main__:Unexpected error
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/__main__.py", line 193, in main
    async for _timestamp, event_type, event_data in stream(
  File "/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/remote.py", line 35, in stream
    message_id, handler_id = await _start_pipeline(
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/remote.py", line 119, in _start_pipeline
    assert msg["success"], "Pipeline failed to run"
AssertionError: Pipeline failed to run
```
 
This is the configuration of my Assist Microphone add on

<img width="664" alt="image" src="https://github.com/rhasspy/hassio-addons/assets/136709923/25f0abfa-3bb7-4bc3-837b-36199886fe84">

<img width="885" alt="image" src="https://github.com/rhasspy/hassio-addons/assets/136709923/94b7b3a9-d7d0-4815-95ce-3eb6a2bcbb48">

Can you help me in fixing this?

**Comment by synesthesiam** [comment]
Are you able to run the pipeline with wake word detection successfully from the debug panel?

https://www.home-assistant.io/voice_control/troubleshooting/

**Comment by synesthesiam** [comment]
This shouldn't be a requirement. I'll make a note of it and check into pipelines without TTS. Thanks!
