### ISSUE TITLE
Assist Microphone - Awake Sound played 5-8x in row randomly

### ISSUE THREAD

**Issue by ms1design** [rhasspy/hassio-addons#31]
The issues Ive got is sometimes the Assist Microphone Add-on is playing 5-8x Awake sound just one-after-one. This happens in different situations:
- when listening to TV speaking
- when everything is off and it's quiet

Ive checked the logs when that happens, but theres nothing in **Assist Microphone Add-on** or `openWakeWord` - just like it's fired 5-8x times randomly just the Awake Sound.

This prevents me from running Assist Mic Add-on at the full scale.

My system
Proxmox VM with HA OS (pass through sound card & Anker PowerConf S330)
Home Assistant 2023.10.2
Supervisor 2023.10.0
Operating System 10.5
UI 20231005.0 - latest

Connected Speakers/Mics/Sound Cards
Anker PowerConf S330 (USB) - chosen in Assist Microphone Add-on configuration
External SoundCard used by Mopidy Add-on (later I removed it without any impact on issue)
Intel HDA sound card pass through to VM

**Comment by Lampyridae1984** [comment]
+1

Same issue, happens randomly

**Home Assistant Yellow**

 Home Assistant 2023.10.3
Supervisor 2023.10.0
Operating System 11.0
Frontend 20231005.0 - latest

**Comment by synesthesiam** [comment]
Please try the official Assist Microphone add-on: https://github.com/home-assistant/addons/tree/master/assist_microphone

**Comment by TB-SE** [comment]
> Please try the official Assist Microphone add-on: https://github.com/home-assistant/addons/tree/master/assist_microphone

That's what I'm using and I still have static sounds/pops both directly before and after the respons is played through the speaker.
