### ISSUE TITLE
Assist Microphone - USB3 is not recognised

### ISSUE THREAD

**Issue by horvathgergo** [rhasspy/hassio-addons#32]
[HA 2023.10, hardware raspberry pi 4]

I configured openwakeword and assist-microphone but my Dell WH3022 USB headset attached directly to my RPI4 USB3 slot is not recognised by assist-microphone (dropdown list is empty in the configuration section)

![image](https://github.com/rhasspy/hassio-addons/assets/44551566/3c2853cf-5785-4b0e-96b5-74c81fad079a)

However, the device is listed in the hardware section:

![image](https://github.com/rhasspy/hassio-addons/assets/44551566/a4a7c615-398b-4311-8e6b-627405e951d6)

**Comment by Lampyridae1984** [comment]
Try this:

(1) Turn off the add-on
(2) Reboot the system (RPI4) under settings, not HA OS
(3) After reboot, 'Rebuild' the add-on
(4) Check the add-on settings

**Comment by horvathgergo** [comment]
Thanks Tommy, it worked 😃
