### ISSUE TITLE
[Feature Request] Assist Microphone - binary_sensor "Assist in progress"

### ISSUE THREAD

**Issue by Ben-Kaniobi** [rhasspy/hassio-addons#35]
With the M5Stack Atom Echo via ESPHome as input/output device for Voice Assistant, there is the binary_sensor "Assist in progress".
It would be usefull to have such a sensor also with the Assist Microfone.

That way, for example an indicator LED/Light could be set while Assist is listening. (In that case the awake and done sounds could even be silent as the LED indicator would be enough to know when to speak.)

**Comment by Krull56** [comment]
Hello

I use openwakeword and porcupine state as trigger for light signal when assist is listen and working fine

**Comment by Ben-Kaniobi** [comment]
Hi @Krull56 , thanks for the suggestion.

I've tried it out:
The state of the wake_word entity gives the time/date after it recognized the wake word.
The state of the tts entity gives the start time/date of the text to speech. These entities don't provide other attributes.
With those, I can create a binary sensor which is True while Voice Assist is listening, and False when it is idle:
```yaml
template:
  - binary_sensor:
      - name: "Voice Assistant listening"
        state: "{{ as_timestamp(states('wake_word.porcupine1')) > as_timestamp(states('tts.piper')) }}"
```

But this is only a workaround, and there are two major problems:
* The tts state does not always change (depending on the action?), e.g. when I don't speak, or when it did not understand my phrase. This results in the binary sensor staying True until the next (successful) time.
* The binary sensor is always updated even when I speak to the Echo in the other room, because the wake word and tts engines are used for all inputs. I would like it to be specific to the Assist Microphone.

How exactly are you doing it, what am I missing?

**Comment by Krull56** [comment]
I dont use tts state.
A simple automation with porcupine state as trigger and flash bulb 5 secondes as action to show me when assist start listening.
And no echo or nest in my home 😉

**Comment by synesthesiam** [comment]
This is part of the official Assist Microphone add-on now: https://github.com/home-assistant/addons/tree/master/assist_microphone
