### ISSUE TITLE
[FEATURE REQUEST] HA Entity Mute Speaker Assist-Microphone

### ISSUE THREAD

**Issue by Krull56** [rhasspy/hassio-addons#38]
Hi Mike,

It might be useful to be able to mute the Assist-Microphone speaker directly from an automation or button. 
A mute-speaker entity exposed in HA or a service?

Have a good day

**Comment by synesthesiam** [comment]
This is now part of the official Assist Microphone add-on: https://github.com/home-assistant/addons/tree/master/assist_microphone

**Comment by Krull56** [comment]
Thanks Mike for this add and "Assist State"  in Assist-Microphone. 

Updates fireworks last night ( porcupine, snowboy, Vosk...)  !!! 

Vosk is very fast and accurate for French language.  No information about this new version 1.6  in changelog ?

Have a good day

**Comment by synesthesiam** [comment]
You're welcome!

The vosk update was just to re -enable some languages that I thought were broken (Arabic and Ukrainian), but I tested them again and they were fine.

More coming soon 🙂
