### ISSUE TITLE
Snowboy build arg BUILD_ARCH used as wrong parameter for snowboy_enrollment

### ISSUE THREAD

**Issue by jhbruhn** [rhasspy/hassio-addons#40]
The snowboy_enrollment repository publishes its articats under the arm64 architecture, while this Dockerfile uses the BUILD_ARCH parameter, which is aarch64 in the case of arm64.

This needs to get fixed either here or at snowboy_enrollment.

https://github.com/rhasspy/hassio-addons/blob/bcbd13caa8fce1eb9db3ef9985f3f8f2f4cc9fb2/snowboy/Dockerfile#L30

**Comment by synesthesiam** [comment]
Thanks! This has been resolved now.
