### ISSUE TITLE
Error after Assist Microphone 2.2.2 update

### ISSUE THREAD

**Issue by RickSisco** [rhasspy/hassio-addons#42]
Assist Microphone was working, upgraded to 2.2.2 and get this error.

> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/__main__.py", line 200, in main
>     async for _timestamp, event_type, event_data in stream(
>   File "/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/remote.py", line 28, in stream
>     async with session.ws_connect(url) as websocket:
>   File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1141, in __aenter__
>     self._resp = await self._coro
>                  ^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 779, in _ws_connect
>     resp = await self.request(
>            ^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 425, in _request
>     raise InvalidURL(str_or_url) from e
> aiohttp.client_exceptions.InvalidURL: ws://:8123/api/websocket
> DEBUG:__main__:Waiting for speech
> DEBUG:__main__:Speech detected
> ERROR:__main__:Unexpected error
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 423, in _request
>     url = self._build_url(str_or_url)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 357, in _build_url
>     url = URL(str_or_url)
>           ^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/yarl/_url.py", line 188, in __new__
>     raise ValueError("Invalid URL: host is required for absolute urls")
> ValueError: Invalid URL: host is required for absolute urls
>

**Comment by luca-angemi** [comment]
Is there a way to downgrade add ons version in the meantime?

**Comment by synesthesiam** [comment]
Sorry about that! Fixed with 2.2.3
