### ISSUE TITLE
Assist Microphone - Multiple USB Speakerphones

### ISSUE THREAD

**Issue by that1guy** [rhasspy/hassio-addons#45]
Is it possible to have multiple USB speakerphones and route tts responses to each respective speakerphone.

**Comment by synesthesiam** [comment]
Keep an eye on the official Assist Microphone add-on: https://github.com/home-assistant/addons/tree/master/assist_microphone

It's no possible at the moment, but it uses a proper HA device that should be something we can target as a media player in the future.
