### ISSUE TITLE
Assist Microphone Addon: microphone detected but does not pickup any audio

### ISSUE THREAD

**Issue by alfwro13** [rhasspy/hassio-addons#46]
Hi, for the last couple of days I was playing with Assist Microphone Add-on for HA. Unfortunately I cannot get it working. I can see the microphone is detected but nothing happens. I know that the open_wakeword addon works fine as I can test it via assist in the web browser (over https connection). I am using a generic mic/speaker set (like this one: https://www.aliexpress.com/item/1005005929228163.html). I tested it on my standalone debian pc and that worked without any drivers (plug and play).

### My system
Proxmox VM with HA OS (pass through USB hub and generic mic/speaker)
Home Assistant 2023.10.5
Supervisor 2023.10.1
Operating System 11.1
Frontend 20231005.0

Connected Speakers/Mics/Sound Cards - speaker/mic connected to a pass through hub that I know it is working as I have my zwave stick connected to it and HA is correctly detecting that speaker/mic device:

### ha audio info   
````                                                                                          
audio:
  application:
  - addon: 47701997_assist_microphone
    index: 2
    mute: false
    name: ALSA plug-in [aplay]
    stream_index: 1
    stream_type: input
    volume: 1
  card:
  - driver: module-alsa-card.c
    index: 0
    name: alsa_card.usb-BY_BY_Y02_20180508-00
    profiles:
    - active: false
      description: Analog Stereo Input
      name: input:analog-stereo
    - active: false
      description: Digital Stereo (IEC958) Input
      name: input:iec958-stereo
    - active: false
      description: Analog Stereo Output
      name: output:analog-stereo
    - active: true
      description: Analog Stereo Duplex
      name: output:analog-stereo+input:analog-stereo
    - active: false
      description: Analog Stereo Output + Digital Stereo (IEC958) Input
      name: output:analog-stereo+input:iec958-stereo
    - active: false
      description: Digital Stereo (IEC958) Output
      name: output:iec958-stereo
    - active: false
      description: Digital Stereo (IEC958) Output + Analog Stereo Input
      name: output:iec958-stereo+input:analog-stereo
    - active: false
      description: Digital Stereo Duplex (IEC958)
      name: output:iec958-stereo+input:iec958-stereo
    - active: false
      description: "Off"
      name: "off"
  input:
  - applications:
    - addon: 47701997_assist_microphone
      index: 2
      mute: false
      name: ALSA plug-in [aplay]
      stream_index: 1
      stream_type: input
      volume: 1
    card: 0
    default: true
    description: BY Y02 Analog Stereo
    index: 1
    mute: false
    name: alsa_input.usb-BY_BY_Y02_20180508-00.analog-stereo
    volume: 0.5495452880859375
  output:
  - applications: []
    card: 0
    default: true
    description: BY Y02 Analog Stereo
    index: 2
    mute: false
    name: alsa_output.usb-BY_BY_Y02_20180508-00.analog-stereo
    volume: 0.860992431640625
host: 172.30.32.4
update_available: false
version: 2023.06.0
version_latest: 2023.06.0
````

### Assist Microphone Logs
````
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service assist_microphone: starting
s6-rc: info: service assist_microphone successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
DEBUG:__main__:Namespace(host='homeassistant', token='REMOVED', port=8123, api_path='/api', pipeline='', protocol='http', mic_device=None, snd_device=None, mic_command=None, snd_command=None, snd_command_sample_rate=22050, awake_sound='/usr/src/sounds/awake.wav', done_sound='/usr/src/sounds/done.wav', volume=1.0, vad='silero', vad_model=PosixPath('/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/models/silero_vad.onnx'), vad_threshold=0.5, vad_trigger_level=3, vad_buffer_chunks=40, wake_buffer_seconds=0.0, noise_suppression=2, auto_gain=15, volume_multiplier=1.0, udp_mic=None, udp_snd=None, udp_snd_sample_rate=22050, debug_recording_dir='', debug=True)
DEBUG:__main__:Waiting for speech
DEBUG:__main__:Using webrtc audio processing
2023-10-29 12:20:41.278480944 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '131'. It is not used by any node and should be removed from the model.
2023-10-29 12:20:41.278540429 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '136'. It is not used by any node and should be removed from the model.
2023-10-29 12:20:41.278552608 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '139'. It is not used by any node and should be removed from the model.
2023-10-29 12:20:41.278561751 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '140'. It is not used by any node and should be removed from the model.
2023-10-29 12:20:41.278570442 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '134'. It is not used by any node and should be removed from the model.
2023-10-29 12:20:41.278638153 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '628'. It is not used by any node and should be removed from the model.
2023-10-29 12:20:41.278650253 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '623'. It is not used by any node and should be removed from the model.
2023-10-29 12:20:41.278659081 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '629'. It is not used by any node and should be removed from the model.
2023-10-29 12:20:41.278667310 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '620'. It is not used by any node and should be removed from the model.
2023-10-29 12:20:41.278688366 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '625'. It is not used by any node and should be removed from the model.
DEBUG:__main__:Using silero VAD
DEBUG:root:Microphone command: ['arecord', '-r', '16000', '-c', '1', '-f', 'S16_LE', '-t', 'raw']
Recording raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
````
Where am I going wrong? 
Thanks

**Comment by scoudibou** [comment]
Hello, same situation for me. 
Everything seems ok but the wake work is never detected. 
I've tried the same pipeline with my phone and assist and it works, I've done an esp32+mic (with wakeword enable) and it works but nothing with the embedded Assist Microphone USB. The microphone is detected, seems to work but not...
I've already used this mic with Rhasspy and it's working like a charm.

Configuration :
- Home Assistant in VM with microphone USB passthrough on server 1.
- Dockered pipeline (Piper, OpenWakeword and Whisper) in LXC on server 2 (i've tested the Pipeline integrated in the Home Assistant VM but CPU was nearly at 100% and needed 5-10 seconds for STT, now i'm at 1 second for STT).

The only thing i see in the logs is "mic_device=None, snd_device=None, mic_command=None, snd_command=None" even if the mic is detected. Is it normal to have mic_device to None ?
If I remove the mic I've this kind of logs : 
`ALSA lib pcm_pulse.c:758:(pulse_prepare) PulseAudio: Unable to create stream: No such entity

arecord: set_params:1416: Unable to install hw params:
ACCESS:  RW_INTERLEAVED
FORMAT:  S16_LE
SUBFORMAT:  STD
SAMPLE_BITS: 16
FRAME_BITS: 16
CHANNELS: 1
RATE: 16000
PERIOD_TIME: 125000
PERIOD_SIZE: 2000
PERIOD_BYTES: 4000
PERIODS: 4
BUFFER_TIME: 500000
BUFFER_SIZE: 8000
BUFFER_BYTES: 16000
TICK_TIME: [0 0]`

that make me thinking that when plugged the mic is well detected.

Here is a typical log block :
`DEBUG:__main__:Speech detected
DEBUG:homeassistant_satellite.remote:{'type': 'auth_required', 'ha_version': '2023.10.5'}
DEBUG:homeassistant_satellite.remote:{'type': 'auth_ok', 'ha_version': '2023.10.5'}
DEBUG:homeassistant_satellite.remote:{'id': 1, 'type': 'result', 'success': True, 'result': None}
DEBUG:homeassistant_satellite.remote:{'id': 1, 'type': 'event', 'event': {'type': 'run-start', 'data': {'pipeline': '01hdbn06ae95fpv1nwabgedd0e', 'language': 'fr', 'runner_data': {'stt_binary_handler_id': 1, 'timeout': 300}}, 'timestamp': '2023-11-01T17:55:08.411465+00:00'}}
DEBUG:homeassistant_satellite.remote:{'id': 1, 'type': 'event', 'event': {'type': 'wake_word-start', 'data': {'entity_id': 'wake_word.openwakeword', 'metadata': {'format': 'wav', 'codec': 'pcm', 'bit_rate': 16, 'sample_rate': 16000, 'channel': 1}, 'timeout': 3}, 'timestamp': '2023-11-01T17:55:08.411584+00:00'}}
DEBUG:__main__:wake_word-start {'entity_id': 'wake_word.openwakeword', 'metadata': {'format': 'wav', 'codec': 'pcm', 'bit_rate': 16, 'sample_rate': 16000, 'channel': 1}, 'timeout': 3}
DEBUG:homeassistant_satellite.remote:{'id': 1, 'type': 'event', 'event': {'type': 'error', 'data': {'code': 'wake-word-timeout', 'message': 'Wake word was not detected'}, 'timestamp': '2023-11-01T17:55:10.193578+00:00'}}
DEBUG:__main__:error {'code': 'wake-word-timeout', 'message': 'Wake word was not detected'}
DEBUG:homeassistant_satellite.remote:{'id': 1, 'type': 'event', 'event': {'type': 'run-end', 'data': None, 'timestamp': '2023-11-01T17:55:10.193647+00:00'}}
DEBUG:__main__:run-end None
DEBUG:homeassistant_satellite.remote:Pipeline finished
DEBUG:__main__:Waiting for speech`

This kind of message is even showed without speech / noise..
I've tried differents VAD settings without success.

If I look at OpenWakeword logs I only have : 
`2023-11-01T20:45:19.513748000Z DEBUG:wyoming_openwakeword.handler:Client connected: 18811434431372
2023-11-01T20:45:19.514012000Z DEBUG:wyoming_openwakeword.handler:Receiving audio from client: 18811434431372
2023-11-01T20:45:21.708255000Z DEBUG:wyoming_openwakeword.handler:Client disconnected: 18811434431372`

But the wake word is never triggered.
Here is an example  with my esp32 sat : 
`2023-11-01T20:39:30.472160000Z DEBUG:wyoming_openwakeword.handler:Client connected: 18462392791432
2023-11-01T20:39:30.472436000Z DEBUG:wyoming_openwakeword.handler:Receiving audio from client: 18462392791432
2023-11-01T20:39:33.325156000Z DEBUG:root:Triggered alexa_v0.1 (client=18462392791432)
2023-11-01T20:39:33.331786000Z DEBUG:wyoming_openwakeword.handler:Client disconnected: 18462392791432`

It makes me thinking that it could be mic settings.

Any idea or advice ?

Thanks!

**Comment by scoudibou** [comment]
Hello,

I'm beginning to have result.
My USB Mic was at 100% volume in HA. I think it was saturated voice. I've put it down to 50 % (ha audio volume input --index 0 --volume 50). I've disable noise reduction. 
It's still not very accurate but it begin to works. I'm trying to finetune it.
If someone has advice to help to be more accurate...

Regards

**Comment by scoudibou** [comment]
whisper base model is not sufficient for me to recognize wake word (alexa) I needed to switch to small-int8 to make it works (with 7 seconds of delay on a dedicated lxc for pipeline...)

**Comment by pablinho1023** [comment]
I am having the same issue, my log also gets stuck at 
`Recording raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono`
I think it is a missing configuration from home assistant and the raspberry pi, where the pi doesn't select correctly the audio hardware. I have bring this up multiple times but developers just ignore it.

**Comment by wardozer** [comment]
I am also in the same situation, stuck at
Recording raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono

**Comment by synesthesiam** [comment]
Please try the official Assist Microphone add-on: https://github.com/home-assistant/addons/tree/master/assist_microphone
