### ISSUE TITLE
Assist Microphone: Adjust volume input

### ISSUE THREAD

**Issue by pako-github** [rhasspy/hassio-addons#53]
I am using a avusio microphone connect via USB to a RPi 4. The voice assistant worked only if I was speaking very close to the microphone. The sound files received through the debug options were very quiet. Any tweakings through the configuration of the addon didn't work. But then I adjusted the input volume via `ha audio volume input --index ... --volume XX` and it works very smooth now. Do I miss a configuration from the addon? I don't want to log every time into the HA shell to adjust the input volume of the mic.

**Comment by synesthesiam** [comment]
Try using the official Assist Microphone add-on: https://github.com/home-assistant/addons/tree/master/assist_microphone

Increase the "volume multiplier" setting to bump the microphone volume up.
