### ISSUE TITLE
wrong github repo link in the Rhasspy addon web page

### ISSUE THREAD

**Issue by litinoveweedle** [rhasspy/hassio-addons#6]
Hello, in the HA Rhasspy addon web page there is text:

```
Offline voice assistant for Home Assistant.
Visit Rhasspy Assistant page for details. 
```
but link itself points to non existing page: https://github.com/synesthesiam/hassio-addons/tree/master/rhasspy

instead of: https://github.com/rhasspy/hassio-addons

**Comment by synesthesiam** [comment]
Thanks! Got it fixed now.
