### ISSUE TITLE
Short question: Was only the VOSK backup behavior changed?

### ISSUE THREAD

**Issue by VenominousX** [rhasspy/hassio-addons#64]
Hi Synesthesiam,

like the title mentioned, i only want to know if the change only affect the backup behaviour.
I'am asking because of i do not have a problem with backuping all dependencies, which means, that if i have to restore a backup from scratch, i do not need to install these things again.

So if this change only affect the backup behaviour, then i will switch back to the prevoius version. Otherwise it would be great, if this behaviour will become an option under configuration.
 
Many thanks for your hard work and the possibility to control my home only with voice :)

Best regards
Marcus

**Comment by synesthesiam** [comment]
Yes, I believe the only real change was the backup behavior. Sorry for the late response!
Glad the add-on is working for you 🙂
