### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by Spp595** [rhasspy/hassio-addons#66]
where can i find docker container to work this in home assistant docker version

**Comment by dekiesel** [comment]
I'd like to know too. Vosk seems to be the best option for me, but I don't run hassio.

Any help is appreciated!

**Comment by dekiesel** [comment]
I created a [vosk standalone container](https://github.com/dekiesel/wyoming-vosk-standalone/) by ~~shamelessly stealing from this repo~~ getting inspiration from this repo.
